### ISSUE TITLE
Minecraft dataset for pretraining

### ISSUE THREAD

**Issue by YuRuiii** [mazpie/genrl#2]
Hi, mazpie! 

I have been following this wonderful work, which was truly ground-breaking and inspiring! I am also trying to reproduce the results on the Minecraft task. If it’s not too much trouble, could you kindly let me know if there is a Minecraft dataset available?

Thank you so much for your help!

**Comment by mazpie** [comment]
Hi @YuRuiii,

sorry for the wait! I have uploaded the Minecraft dataset I have used for the experiments in the paper on HuggingFace.

If you use it, take into consideration the fact that *for Minecraft standards* is a small dataset (only 4M steps) and that only a few useful behaviors are achieved by the agent (e.g. obtaining logs, planks, sticks).

You can find the data here: https://huggingface.co/datasets/mazpie/genrl_datasets

P.S. since the dataset was larger than 50GB it was split using the `split` command in Linux before uploading. You can simply do `cat minecraft_data.tar.gz.part* > minecraft_data.tar.gz` to put the files back together.

**Comment by YuRuiii** [comment]
Hi! Thank you so much for your response! 

May I ask which Minecraft benchmark you were using, was it MineDojo or MineRL? Additionally, are the agents you used for sampling still DreamerV3 and Plan2Explore?

Thank you again for your help :)

**Comment by mazpie** [comment]
I used only DreamerV3 to collect the data. You can use their [repository](https://github.com/danijar/dreamerv3/tree/main) as a reference for how to setup the environment (which is based onM dreaineRL).
